### ISSUE TITLE
Lasagne version

### ISSUE THREAD

**Issue by benn94** [ccny-ros-pkg/concreteIn_inpection_VGGF#3]
It is said to be Lasagne version: '0.1', but the adjustment in Lasagne has attribute "collect_shared_vars" of Lasagne version: '0.2' which also causes errors in training.py.
It would be nice if you could help with this issue

**Comment by benn94** [comment]
Solved: just copy and past those attribute into your related lasagne files

**Comment by ccny-ros-pkg** [comment]
Great. Sorry for late reply. I will update a pytorch version of this using VGG and Resnet after Nov. 16th. Please check it out them.

**Comment by benn94** [comment]
Looking forwards to seeing your update. @ccny-ros-pkg
